[package]
name = "multitool-telegram-bot-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
teloxide = { version = "0.13", features = [
    "macros",
    "cbor-serializer",
    "sqlite-storage-rustls",
    "sqlite-storage-nativetls",
] }

tokio = "1.43.0"
